version: "3"
services:
  web:
    build: frontend_svc
    ports: 
      - 8080:8080
    network_mode: 'host'
  go:
    build: backendGO
    # depends_on:
    #   - db
    ports:
      - 8082:8082
    network_mode: 'host'
  python:
    build: backend_svc
    # depends_on:
    #   - db
    ports:
      - 8081:8081
    network_mode: 'host'